server:
  port: 8761
#Eureka Specifics
eureka:
  datacenter: Main
  environment: prod
  instance:
    hostname: discovery-service
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
        #include: bus-env
spring: 
  rabbitmq:
    host: rabbit-server
    port: 5672
    username: abstract
    password: >-
      {cipher}AQBpx0l+T9zbvZ2M97tX2xfxjv3lc0ptyRzFkJnxKrGJmj2OQTnAtfRoRCIET23k8cUGVwncJScNLzeMQGvFgjbJ96FlSE19FKJ1/R1R1zyPdUoP/26iiy1U0xT6obxyY5MaqY4i26bu6ac6GitjAl3VCo0CGOgUMSRuVbrVhnuGjhSJSZxfufbWV5kWBhfQGLiLQwf/LxjtzvBPWrCASyhFBRXkEQ8yUIPtoqiWl7jv/f4GNvikDsB0PtcvQ7hF0BZmMx8MvmXZUrY9mpsXMMUEc8yrATwxRGqti5ytd2A3obTiywc1A3LkjlMTmfcC4FnSFRtBpVv4cy+8TEK72jx7lqWVMK5wwMFJDtK3EdvvM2ZDkPz1ZSgLSnckhCPX2oE=
  security:
    user:
      name: abstract
      password: >-
        {cipher}AQBpx0l+T9zbvZ2M97tX2xfxjv3lc0ptyRzFkJnxKrGJmj2OQTnAtfRoRCIET23k8cUGVwncJScNLzeMQGvFgjbJ96FlSE19FKJ1/R1R1zyPdUoP/26iiy1U0xT6obxyY5MaqY4i26bu6ac6GitjAl3VCo0CGOgUMSRuVbrVhnuGjhSJSZxfufbWV5kWBhfQGLiLQwf/LxjtzvBPWrCASyhFBRXkEQ8yUIPtoqiWl7jv/f4GNvikDsB0PtcvQ7hF0BZmMx8MvmXZUrY9mpsXMMUEc8yrATwxRGqti5ytd2A3obTiywc1A3LkjlMTmfcC4FnSFRtBpVv4cy+8TEK72jx7lqWVMK5wwMFJDtK3EdvvM2ZDkPz1ZSgLSnckhCPX2oE=
