
server:
  port: 8080
  use-forward-headers: true
spring:
  banner: 
    charset: utf-8
  info:
    build:
      encoding: utf-8
    git:
      encoding: utf-8
  messages: 
    encoding: utf-8

db-connection:
  url: jdbc:mysql://generalRDBMS:3306/sessionDB?useUnicode=true&characterEncoding=utf-8
  driverClass: com.mysql.cj.jdbc.Driver
  basePackage: com.micro.env
  user: root
  password: {cipher}AQAD6D9bLCwJvYaFh9PSivdzvoXoVwy5D9468bFfIIUYICqTw9Av/Mq33jg0zVaRSR13HZX3oiq8ZaFncBEzfWR1KWqPvLVpj4w71NeKxFoPmclU1D+rOlN+8uzxiMvURKUnjrscS/9dtCUSd4vyVIkKbktZyrXoltBjLef7jYF63clkgGmGrBCS8X1TAKPmym5OaSVX85YGESt82C12lGS/9u0WTY1f6KfJ8wWRQ2MTtFg3JVUDEn/vmV8qn2NUIz/x9n4j3VT69ueWvM8V05hv/VJkJrqS6tYk43f1QKVyDUK3Rn4UwzFqLrIsET6v/yQ0UE2N8oujdykPl7Hq8klEl4qMYny2HPoJdCQvX6KAXz1nhS02NKugfSeltZnI+vA=

feign-ext:
  retryPeriod: 1000
  retryMaxPeriod: 8000
  retryMaxAttempts: 3
  requestConnectTimeoutMill: 5000
  readTimeoutMill: 30000

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    instance:
      preferIpAddress: true
      
management: 
    endpoints: 
        web: 
          exposure:
            include: refresh
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

base-config:
  jwtSecret: qyTs9x99vxnxoV4au5c1KMssFztlgZeW4pNRKEoQ8yN0k33eZPcMBqHMLdMODZIeDzvwUmPXWzdIkUaMg4C0GN1M1XJnDSmWNPbtV3zchboHqpRy1XvdsnhRqJL2lgekSutc7GjPghcxc2Ug452iRCww0syq1owQNxcbNOIzKiHJmhVTXQBafriGevgYPoZsqvScjIOZvFFRNgh4ptxhcRQA5SSHUIhJtuZZWInog4fZ1OuCTWIumsBC1FQpw0d

