server:
  port: 8080
  use-forward-headers: true
spring:
  main:
    banner-mode: "off"
  rabbitmq:
    host: rabbit-server
    port: 5672
    username: abstract
    password: >-
      {cipher}AQBpx0l+T9zbvZ2M97tX2xfxjv3lc0ptyRzFkJnxKrGJmj2OQTnAtfRoRCIET23k8cUGVwncJScNLzeMQGvFgjbJ96FlSE19FKJ1/R1R1zyPdUoP/26iiy1U0xT6obxyY5MaqY4i26bu6ac6GitjAl3VCo0CGOgUMSRuVbrVhnuGjhSJSZxfufbWV5kWBhfQGLiLQwf/LxjtzvBPWrCASyhFBRXkEQ8yUIPtoqiWl7jv/f4GNvikDsB0PtcvQ7hF0BZmMx8MvmXZUrY9mpsXMMUEc8yrATwxRGqti5ytd2A3obTiywc1A3LkjlMTmfcC4FnSFRtBpVv4cy+8TEK72jx7lqWVMK5wwMFJDtK3EdvvM2ZDkPz1ZSgLSnckhCPX2oE=
  info:
    build:
      encoding: utf-8
    git:
      encoding: utf-8
  messages:
    encoding: utf-8

feign-ext:
  retryPeriod: 1000
  retryMaxPeriod: 8000
  retryMaxAttempts: 3
  requestConnectTimeoutMill: 5000
  readTimeoutMill: 30000

eureka:
  credentials:
    username: abstract
    password: >-
      {cipher}AQBpx0l+T9zbvZ2M97tX2xfxjv3lc0ptyRzFkJnxKrGJmj2OQTnAtfRoRCIET23k8cUGVwncJScNLzeMQGvFgjbJ96FlSE19FKJ1/R1R1zyPdUoP/26iiy1U0xT6obxyY5MaqY4i26bu6ac6GitjAl3VCo0CGOgUMSRuVbrVhnuGjhSJSZxfufbWV5kWBhfQGLiLQwf/LxjtzvBPWrCASyhFBRXkEQ8yUIPtoqiWl7jv/f4GNvikDsB0PtcvQ7hF0BZmMx8MvmXZUrY9mpsXMMUEc8yrATwxRGqti5ytd2A3obTiywc1A3LkjlMTmfcC4FnSFRtBpVv4cy+8TEK72jx7lqWVMK5wwMFJDtK3EdvvM2ZDkPz1ZSgLSnckhCPX2oE=
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.credentials.username}:${eureka.credentials.password}@discovery-service:8761/eureka/
    instance:
      preferIpAddress: true  


management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
        #include: bus-env

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
